[package]
name = "fastquote-tdx"
version = "0.1.0"
edition = "2021"

[dependencies]
fastquote-core = { path = "../fastquote-core" }
tokio = { workspace = true }
bytes = { workspace = true }
nom = { workspace = true }
encoding_rs = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
